swagger: '2.0'

info:
  version: "0.0.4"
  title: Wave Application
host: localhost:9600
basePath: /
tags:
  - name: "user"
  - name: "session"
  - name: "websocket"
schemes:
  - http
paths:
  /users:
    post:
      tags:
      - user
      summary: "Create an account."
      about: ""
      operationId: signupUser
      consumes:
        - "multipart/form-data"
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          about: "Key user information."
          required: true
          schema:
            $ref: "#/definitions/UserExtended"
      responses:
        201:
          about: Created
        403:
          about: Forbidden
          schema:
            $ref: "#/definitions/ForbiddenRequest"
        500:
          about: Internal Server Error
  /users/me:
    get:
      tags:
      - user
      summary: "Get current user's information."
      about: ""
      operationId: myProfile
      consumes: []
      produces:
        - application/json
      responses:
        200:
          about: OK
          schema:
            $ref: "#/definitions/UserExtended"
        401:
          about: Unauthorized
        500:
          about: Internal Server Error
    put:
      tags:
      - user
      summary: "Update current user's profile."
      about: ""
      operationId: updateMyProfile
      consumes:
        - "multipart/form-data"
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          about: "New user information."
          required: true
          schema:
            $ref: "#/definitions/UserEdit"
      responses:
        200:
          about: OK
        401:
          about: Unauthorized
        403:
          about: Forbidden
          schema:
            $ref: "#/definitions/ForbiddenRequest"
        500:
          about: Internal Server Error
  /users/{name}:
    get:
      tags:
      - user
      summary: "Get another user's information."
      about: ""
      operationId: usersProfile
      consumes: []
      produces:
        - application/json
      parameters:
      - in: path
        name: name
        type: string
        required: true
        about: Target username.
      responses:
        200:
          about: OK
          schema:
            $ref: "#/definitions/UserExtended"
        404:
          about: Not Found
        500:
          about: Internal Server Error

  /users/leaders?count=${count}&page=${page}:
     get:
      tags:
      - user
      summary: "Get all users with their scores."
      about: ""
      operationId: leaders
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        406:
          about: Not Acceptable
        400:
          about: Bad Request
        200:
          about: OK
          schema:
            $ref: "#/definitions/Leaderboard"
        500:
          about: Internal Server Error

  /session:
    post:
      tags:
      - session
      summary: "Log in into an existing account."
      about: ""
      operationId: loginUser
      consumes:
        - "multipart/form-data"
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          about: "User credentials."
          required: true
          schema:
            $ref: "#/definitions/UserCredentials"
      responses:
        200:
          about: OK
        401:
          about: Unauthorized
          schema:
            $ref: "#/definitions/ForbiddenRequest"
        500:
          about: Internal Server Error
    delete:
      tags:
      - session
      summary: "Log out from the current account."
      about: ""
      operationId: logoutUser
      consumes: []
      responses:
        200:
          about: OK
        500:
          about: Internal Server Error
  
  /conn/lobby:

definitions:
  ForbiddenRequest:
    type: object
    properties:
      reason:
        type: string
        example: <reason>

  Pagination:
    type: object
    required:
      - page
      - count
    properties:
      page:
        type: integer
        minimum: 0
        example: 0
      count:
        type: integer
        minimum: 0
        example: 5

  UserScore:
    type: object
    required:
      - username
      - score
    properties:
      username:
        type: string
        example: <username>
      score:
        type: integer
        example: 0

  Leaderboard:
    type: object
    properties:
      users:
        type: array
        items:
          $ref: "#/definitions/UserScore"
      total:
        type: integer
        minimum: 0
        example: 0

  UserCredentials:
    type: object
    required:
      - "username"
      - "password"
    properties:
      username:
        type: string
        example: florence
      password:
        type: string
        example: pass123

  UserExtended:
    type: object
    properties:
      username:
        type: string
        example: florence
      score:
        type: integer
        example: 21
      avatar:
        type: byte
        example: <avatar>

  UserEdit:
    type: object
    properties:
      username:
        type: string
        example: florence
      password:
        type: string
        example: mypass123
      avatar:
        type: byte
example: <avatar>